services:
  app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev
    env_file:
      - ../.env.dev
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ../
          target: /app
          ignore:
            - node_modules/

  db:
    image: postgres:18
    restart: always
    volumes:
      - ${PWD}/db-data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pwhlcord_stats
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5