name: 🚀 Deploy
on:
  push:
    branches:
      - main
      - dev
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  lint:
    name: ⬣ ESLint
    runs-on: ubuntu-24.04
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v6

      - name: ⎔ Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 25.2.1

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: 🔬 Lint
        run: npm run lint

  typecheck:
    name: ʦ TypeScript
    runs-on: ubuntu-24.04
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v6

      - name: ⎔ Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 25.2.1

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: 🔎 Type check
        run: npm run typecheck

  vitest:
    name: ⚡ Vitest
    runs-on: ubuntu-24.04
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v6

      - name: ⎔ Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 25.2.1

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: 🏄 Copy test env vars
        run: cp .env.example .env

      - name: ⚡ Run vitest
        run: npm run test
